#!/bin/bash

# docker install on ubuntu-22.04
# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04


sudo apt-get -y update
sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get -y update
apt-cache policy docker-ce
sudo apt-get -y install docker-ce
sudo usermod -aG docker ${USER}

# https://serverfault.com/questions/1005648/docker-changes-iptables-forward-policy-to-drop
# temp
# sudo iptables -I DOCKER-USER  -j ACCEPT

# perm
cat <<'EOF' | sudo bash -
echo "net.ipv4.ip_forward=1" >>/etc/sysctl.conf
echo "net.ipv6.conf.all.forwarding=1" >>/etc/sysctl.conf
EOF


