#!/bin/bash
osascript -e 'tell application "Microsoft Edge" to make new window'
#eom
#sleep 3
open -a "Microsoft Edge" \
  https://digital.fidelity.com/ftgw/digital/traderplus \
  https://digital.fidelity.com/ftgw/digital/portfolio/positions \
  https://digital.fidelity.com/ftgw/digital/portfolio/activity \
  https://digital.fidelity.com/ftgw/digital/planning-summary/ \
  https://www.google.com/finance/ \

