#!/bin/bash
osascript -e 'tell application "Google Chrome" to make new window'
#eom
#sleep 3
open -a "Google Chrome" https://digital.fidelity.com/ftgw/digital/trader-dashboard
#sleep 2
open -a "Google Chrome" https://digital.fidelity.com/ftgw/digital/portfolio/positions
#sleep 2
open -a "Google Chrome" https://digital.fidelity.com/ftgw/digital/portfolio/activity
#sleep 2
open -a "Google Chrome" https://digital.fidelity.com/ftgw/digital/planning-summary/
open -a "Google Chrome" https://www.google.com/finance/

