#!/usr/bin/env python

import sys
import json
import re
import csv
import os
import glob

input_file = None
if len(sys.argv) > 1:
    candidate = sys.argv[1]
    if os.path.isfile(candidate):
        input_file = candidate
    else:
        print(f"Error: Provided file '{candidate}' does not exist.", file=sys.stderr)
        sys.exit(1)

if not input_file:
    dirs_to_check = ['~', '~/Desktop', '~/Desktop/x', '~/Downloads', '.']
    matching_files = []
    for d in dirs_to_check:
        expanded_dir = os.path.expanduser(d)
        pattern = os.path.join(expanded_dir, 'Portfolio_Positions*.csv')
        matching_files.extend(glob.glob(pattern))
    
    unique_files = list(set(os.path.abspath(f) for f in matching_files if os.path.isfile(f)))
    
    if unique_files:
        input_file = max(unique_files, key=os.path.getmtime)
        print(f"Using latest file: {input_file}", file=sys.stderr)
    else:
        print('Need "Overview" downloaded from https://digital.fidelity.com/ftgw/digital/portfolio/positions', file=sys.stderr)
        print('Could not find any Portfolio_Positions*.csv file in ~, ~/Desktop, ~/Desktop/x, ~/Downloads, or .', file=sys.stderr)
        sys.exit(1)

things = {}
with open(input_file, 'rt', encoding='utf-8') as f:
    csvFile = csv.DictReader(f)
    for line in csvFile:
        # print(json.dumps(line, indent=2))
        # {
        #   "\ufeffAccount Number": "X96600886",
        #   "Account Name": "Brok1$328k-2025.05.06",
        #   "Symbol": "SPAXX**",
        #   "Description": "HELD IN MONEY MARKET",
        #   "Quantity": "",
        #   "Last Price": "",
        #   "Last Price Change": "",
        #   "Current Value": "$83865.00",
        #   "Today's Gain/Loss Dollar": "",
        #   "Today's Gain/Loss Percent": "",
        #   "Total Gain/Loss Dollar": "",
        #   "Total Gain/Loss Percent": "",
        #   "Percent Of Account": "19.04%",
        #   "Cost Basis Total": "",
        #   "Average Cost Basis": "",
        #   "Type": "Cash"
        # }
        # {
        #   "\ufeffAccount Number": "X96600886",
        #   "Account Name": "Brok1$328k-2025.05.06",
        #   "Symbol": " -NVO270115C60",
        #   "Description": "NVO JAN 15 2027 $60 CALL",
        #   "Quantity": "59",
        #   "Last Price": "$5.80",
        #   "Last Price Change": "-$0.35",
        #   "Current Value": "$34220.00",
        #   "Today's Gain/Loss Dollar": "-$1903.67",
        #   "Today's Gain/Loss Percent": "-5.27%",
        #   "Total Gain/Loss Dollar": "-$14740.52",
        #   "Total Gain/Loss Percent": "-30.11%",
        #   "Percent Of Account": "7.77%",
        #   "Cost Basis Total": "$48960.52",
        #   "Average Cost Basis": "$8.30",
        #   "Type": "Cash"
        # }
        if line['Symbol'] is not None:
            if 'CALL' not in line['Description']:
                continue
            symbol = line['Symbol']          # " -NVO270115C60"
            value = line['Current Value']    # "$34220.00"
            basis = line['Cost Basis Total'] # "$48960.52"
            symbol = re.sub(r'^\s\-', '', symbol)
            symbol = re.sub(r'\d.*', '', symbol)
            if symbol == 'Pending activity':
                continue
            if symbol == '**':
                continue
            if symbol == '':
                continue

            value = re.sub(r'^\$', '', value)
            if value == '--':
                value = 0
            else:
                value = float(value)
            basis = re.sub(r'^\$', '', basis)
            if basis == '':
                basis = value
            elif basis == '--':
                basis = 0
            else:
                basis = float(basis)
            if symbol not in things:
                things[symbol] = {}
                things[symbol]['basis'] = 0
                things[symbol]['value'] = 0
            things[symbol]['basis'] += basis
            things[symbol]['value'] += value

print(f'Value\tBasis\tGain\t%Gain\tSymbol')
for symbol in things:
    value = things[symbol]['value']
    basis = things[symbol]['basis']
    gain = value - basis
    if basis != 0:
        pgain = gain * 100 / basis
        pgain = f'{pgain:.2f}'
    else:
        pgain = ''
    print(f'{value:.2f}\t{basis:.2f}\t{gain:.2f}\t{pgain}\t{symbol}')
