#!/bin/bash
cd ~/gcode/fin/names
../nms 00NOW.txt | grep '^ '|tr ' ' '\n'|sort -u >.now.txt
mv 00NOW.txt 00NOW.txt.1
cat *.txt >.all.txt.1
../nms .all.txt.1 | grep '^ '|tr ' ' '\n'|sort -u >.all.txt
rm -f .all.txt.1
mv 00NOW.txt.1 00NOW.txt
comm -23 .now.txt .all.txt
rm -f .now.txt .all.txt

