#!/bin/bash
if [[ $1 == '' ]]; then
    exit 0
fi

for f in "$@"; do
    if [[ ! -f "$f" ]]; then
        continue
    fi
    if [[ $f =~ .csv$ ]]; then
        ~/gcode/fin/syms "$f"
        continue
    fi
    echo "$f" | sed 's/\.txt$//; s,^.*/,,'
    cat "$f" | perl -pe 's/\#.*//; s/\b\d+\b//; s/\s/\n/gs' | sort -u| xargs -L 20|sed 's/^/    /'
    echo
done
