#!/bin/bash
if [[ $1 == '' ]]; then
    exit 0
fi

for f in "$@"; do
    if [[ -f "$f" ]]; then
        echo "$f" | sed 's/\.txt$//; s,^.*/,,'
        cat "$f" | perl -pe 's/\#.*//; s/\b\d+\b//; s/\s/\n/gs' | sort -u| xargs -L 20|sed 's/^/    /'
        echo
    fi
done
