#!/usr/bin/env python

import sys
import json
import re

if len(sys.argv) == 1:
    print('Need "Closed positions" downloaded from https://digital.fidelity.com/ftgw/digital/portfolio/positions')
    sys.exit(0)

things = {}
with open(sys.argv[1], 'rt', encoding='utf-8') as f:
    for line in f:
        parts = line.strip().split(',')
        """
          [
            "\ufeffAccount Number",
            "Account Name",
            "Symbol",
            "Description",
            "Cost Basis",
            "Proceeds",
            "Short Term Gain/Loss",
            "Long Term Gain/Loss",
            "Total Term Gain/Loss"
          ],
          [
            "X96600886",
            "Brok1$328k-2025.05.06",
            "AAPL",
            "APPLE INC",
            "$48934.60",
            "$74996.13",
            "+$520.00",
            "+$25541.53",
            "+$26061.53",
            ""
          ],
          [
            "X96600886",
            "Brok1$328k-2025.05.06",
            " -AAPL251219C220",
            "CALL (AAPL) APPLE INC DEC 19 25 $220 (100 SHS)",
            "$92841.48",
            "$122989.82",
            "+$30148.34",
            "",
            "+$30148.34",
            ""
          ],
        """
        if len(parts) == 10:
            symbol = parts[2]
            gain   = parts[8]
            m = re.search(r'^\s*\-?([A-Z]+)(\d.*)?$', symbol)
            if m:
                symbol = m.group(1)
                m = re.search(r'^([\+\-])\$([\d\.]+)$', gain)
                if m:
                    gain = float(m.group(2))
                    if symbol not in things:
                        things[symbol] = 0
                    if m.group(1) == '-':
                        things[symbol] -= float(m.group(2))
                    else:
                        things[symbol] += float(m.group(2))

print('Symbol\tGain')
for s in sorted(things.keys(), key=lambda x: int(things[x]), reverse=True):
    n = int(things[s])
    print(f'{s}\t{n}')



