#!/usr/bin/env python

import sys
import json
import re
import csv

if len(sys.argv) == 1:
    print('Need "Closed positions" downloaded from https://digital.fidelity.com/ftgw/digital/portfolio/positions')
    sys.exit(0)

things = {}
with open(sys.argv[1], 'rt', encoding='utf-8') as f:
    csvFile = csv.DictReader(f)
    for line in csvFile:
        # print(json.dumps(line, indent=2))
        # {
        #   "\ufeffAccount Number": "X96600886",
        #   "Account Name": "Brok1$328k-2025.05.06",
        #   "Symbol": " -WMT261218C100",
        #   "Description": "CALL (WMT) WALMART INC COM DEC 18 26 $100 (100 SHS)",
        #   "Cost Basis": "$37938.59",
        #   "Proceeds": "$45476.43",
        #   "Short Term Gain/Loss": "+$7537.84",
        #   "Long Term Gain/Loss": "--",
        #   "Total Term Gain/Loss": "+$7537.84",
        #   "null": [
        #     ""
        #   ]
        # }
        # {
        #   "\ufeffAccount Number": "X96600886",
        #   "Account Name": "Brok1$328k-2025.05.06",
        #   "Symbol": " -WMT251219C95",
        #   "Description": "CALL (WMT) WALMART INC COM DEC 19 25 $95 (100 SHS)",
        #   "Cost Basis": "$6408.09",
        #   "Proceeds": "$7103.91",
        #   "Short Term Gain/Loss": "+$695.82",
        #   "Long Term Gain/Loss": "--",
        #   "Total Term Gain/Loss": "+$695.82",
        #   "null": [
        #     ""
        #   ]
        # }
        if line['Symbol'] is not None:
            symbol = line['Symbol']
            gain   = line['Total Term Gain/Loss']
            m = re.search(r'^\s*\-?([A-Z]+)', symbol)
            if m:
                symbol = m.group(1)
                m = re.search(r'^([\+\-])\$([\d\.]+)$', gain)
                if m:
                    gain = float(m.group(2))
                    if symbol not in things:
                        things[symbol] = 0
                    if m.group(1) == '-':
                        things[symbol] -= float(m.group(2))
                    else:
                        things[symbol] += float(m.group(2))

print('Symbol\tGain($)')
for s in sorted(things.keys(), key=lambda x: int(things[x]), reverse=True):
    n = int(things[s])
    print(f'{s}\t{n}')



