#!/bin/bash
if [[ -f "$1" ]]; then
    (
    cat "$1" \
    | awk -F"," '{print $3}' \
    | sed 's/^ *//' \
    | egrep -v 'Symbol|SPAXX|Pending|Y00ESC015|FDRXX|CORE|AQB|DE2024905|DE0000907| |\*|[a-z]|^$|^$' \
    | egrep -v '^APEMY$|^VINIX$|^VMCIX$|^GLD$' \
    | sed 's/^-//; s/[0-9].*//' \
    | sort -u \
    | xargs -L 30
    )|sed 's/^/==> /'
else
    echo 'Need positions file'
    echo 'https://digital.fidelity.com/ftgw/digital/portfolio/positions'
fi
