#!/usr/bin/perl
use strict;
my @xcf_files = `ls -1 *.xcf`;

my $join_cmd = "gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=finished.pdf \\\n";

for my $xcf_file (@xcf_files) {
    chomp $xcf_file;
    my $jpg_file = $xcf_file;
    my $pdf_file = $xcf_file;
    $jpg_file =~ s{\.xcf$}{.jpg};
    $pdf_file =~ s{\.xcf$}{.pdf};
    print "convert -density 300 -quality 80 $xcf_file $jpg_file\n";
    my $fileinfo = `file $xcf_file`;
        # om@om-ubs1604:~/a$ file page_0000.xcf
        # page_0000.xcf: GIMP XCF image data, version 0, 2352 x 3124, RGB Color
    if ($fileinfo =~ m{GIMP XCF image data,.+ (\d+) x (\d+)}) {
        my ($x, $y) = ($1, $2);
        my $x_inch = $x / 300;
        my $y_inch = $y / 300;
        $join_cmd .= "    $pdf_file \\\n";
        if ($y > $x) { # portrait
            print "img2pdf -o $pdf_file --imgsize=${x_inch}inx${y_inch}in --pagesize=Letter $jpg_file\n\n";
        }
        else { # landscape
            print "img2pdf -o $pdf_file --imgsize=${x_inch}inx${y_inch}in --pagesize=Letter^T $jpg_file\n\n";
        }
    }
}

print "$join_cmd\n";

