#!/usr/bin/env python3
import sys
import os

def print_help():
    print(sys.argv[0] + ' {pdf-file}')
    print(sys.argv[0] + ' {page1} {pdf-file}')
    print(sys.argv[0] + ' {page1} {page2} {pdf-file}')

if len(sys.argv) == 1:  # ./extracti a.pdf : whole fil
    print_help();
    sys.exit(1)
if len(sys.argv) == 2:  # ./extracti a.pdf : whole fil
    pdf = sys.argv[1]
    if not os.path.isfile(pdf):
        print_help();
        sys.exit(1)
    os.system('rm -rf .out; mkdir .out')
    os.system('pdfimages -all {f} .out/page'.format(f=pdf))
if len(sys.argv) == 3:  # ./extracti 31 /tmp/a.pdf
    pagenum = sys.argv[1]
    pdf = sys.argv[2]
    if not os.path.isfile(pdf):
        print_help();
        sys.exit(1)
    os.system('rm -rf .out; mkdir .out')
    os.system(f'pdftk {pdf} cat {pagenum} output .out/b.pdf')
    os.system(f'cd .out && pdftoppm -png -r 300 b.pdf b')
