#!/bin/bash
if [[ $1 == '' ]]; then
  echo "$0 page pdf-file"
  exit 0
fi
if [[ $2 == '' ]]; then
  echo "$0 page pdf-file"
  exit 0
fi
page=$1
file=$2
pdftk $file cat $page-$page output _a.pdf
pdfimages -j _a.pdf _aa
