#!/bin/bash
if [[ $1 == '' ]]; then
  echo "$0 firstpage lastpage pdf-file [dpi]"
  exit 0
fi
dpi=600
if [[ $4 != '' ]]; then
  dpi=$4
fi
/usr/bin/gs -dNOPAUSE -q -sDEVICE=png16m -r$dpi -dBATCH -dFirstPage=$1 -dLastPage=$2 -sOutputFile=page-%d.png $3
