#!/usr/bin/perl
#use strict;

chdir '/home/om/sb/jencomps/cron/ldap';

$ENV{PATH} = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';

system "echo '---------------------------------------' >>runlog.txt";
system "date >>runlog.txt";
system "hostname >>runlog.txt";
system "id >>runlog.txt";
system "echo '---------------------------------------' >>runlog.txt";

my $home = $ENV{'HOME'};
my ($user, $password) = get_ldap_user_pass();
chomp $password;

my $employees  = "'(memberOf=CN=__PureEmployees,OU=ITGroups,OU=PSGroups,DC=purestorage,DC=com)'";
my $contractors = "'(memberOf=CN=_PureProServices,OU=ITGroups,OU=PSGroups,DC=purestorage,DC=com)'";

my $cmd = <<"__EOF__";
set -x; \\
ldapsearch -o ldif-wrap=no \\
-LLL -z 0 -x \\
-H ldap://ldap.purestorage.com:389 \\
-D '$user' \\
-w '$password' \\
-E pr=2147483647/noprompt \\
-b 'DC=purestorage,DC=com' \\
__PEOPLE__ \\
sAMAccountName \\
manager \\
userPrincipalName \\
slackUsername \\
mobile \\
physicalDeliveryOfficeName \\
streetAddress \\
title \\
givenName \\
sn \\
cn \\
name \\
mail \\
employeeID \\
employeeType \\
division \\
description \\
department \\
departmentNumber \\
uidNumber \\
gidNumber \\
unixHomeDirectory \\
startDate \\
whenCreated \\
__EOF__

my $cmd_emp = $cmd;
my $cmd_con = $cmd;
$cmd_emp =~ s/__PEOPLE__/$employees/;
$cmd_con =~ s/__PEOPLE__/$contractors/;

my @entries = ();
my $node = {};

open RESULT, "$cmd_emp|" or die;
while (my $line = <RESULT>) {
    if ($line eq "\n") {
        if (scalar @{$node->{body}}) {
            push @entries, $node;
        }
        $node = {};
    }
    else {
        next if($line =~ m{^\#});
        if ($line =~ m{^sAMAccountName\s*:\s*(.+?)\s*$}si) {
            $node->{name} = $1;
        }
        push @{$node->{body}}, $line;
    }
}
close RESULT;

open RESULT, "$cmd_con|" or die;
while (my $line = <RESULT>) {
    if ($line eq "\n") {
        if (scalar @{$node->{body}}) {
            push @entries, $node;
        }
        $node = {};
    }
    else {
        next if($line =~ m{^\#});
        if ($line =~ m{^sAMAccountName\s*:\s*(.+?)\s*$}si) {
            $node->{name} = $1;
        }
        push @{$node->{body}}, $line;
    }
}
close RESULT;



@entries = sort {$a->{name} cmp $b->{name}} @entries;

open F, ">allusers.txt.2" or die;
for my $entry (@entries) {
    print F join '', @{$entry->{body}};
    print F "\n";
}
close F;

if (-e 'allusers.txt') {
    system 'diff -q allusers.txt allusers.txt.2';
    if ($? == 0) {
        # Same. No change
        system 'mv -f allusers.txt.2 allusers.txt.2.same';
        exit 0;
    }
    else {
        system "rm -f allusers.txt.2.same";
        my $n1 = `wc -l allusers.txt`;
        my $n2 = `wc -l allusers.txt.2`;
        $n1 =~ s{\s.*}{}s;
        $n2 =~ s{\s.*}{}s;
        if ($n1 - $n2 > 1000) {
            print "Much fewer lines than previous!\n";
            exit 1;
        }

        if (-d 'CVS') {
            system "mv -f allusers.txt.2 allusers.txt; cvs ci -mcheckpoint allusers.txt; cvs up allusers.txt";
        }
        else {
            system "rm -f allusers.txt; co -l allusers.txt; cat allusers.txt.2 >allusers.txt; rm allusers.txt.2; ci -mcheckpoint -u allusers.txt";
        }
    }
}
else {
    if (-d 'CVS') {
        system "mv allusers.txt.2 allusers.txt; cvs add allusers.txt; cvs ci -mcjeckpoint allusers.txt; cvs up allusers.txt";
    }
    else {
        system "mv allusers.txt.2 allusers.txt; ci -t-checkpoint -mcheckpoint -u allusers.txt";
    }
}

sub get_ldap_user_pass {
    my $authfile =  $ENV{HOME}.'/.ssh/ldapauth';
    open F, "<$authfile" or die;
    my $line = <F>;
    close F;
    chomp $line;
    my ($user, $pass) = $line =~ m{^(.+?)\:(.+)$};
    return ("$user\@purestorage.com", $pass);
}
