#!/bin/bash

user=$(cat ~/.ssh/ldapauth| sed 's/:.*//')@purestorage.com
password=$(cat ~/.ssh/ldapauth| sed 's/^.*://')

ldapsearch -o ldif-wrap=no \
-LLL -z 0 -x -h ldap.purestorage.com \
-D "$user" \
-w "$password" \
-E pr=2147483647/noprompt \
-b 'DC=purestorage,DC=com' \
'(memberOf=CN=__PureEmployees,OU=ITGroups,OU=PSGroups,DC=purestorage,DC=com)'
