#!/usr/bin/perl
use strict;


my $text = join ' ', @ARGV;
my $flag = '';
if ($text =~ m{^(\-\S+) (.+)}) {
    $flag = $1;
    $text = $2;
}
$text = quotemeta($text);


my $allusers_file = $ENV{HOME}.'/sb/jencomps/cron/ldap/allusers.txt';
open F, "<$allusers_file" or die "Error: File not found $allusers_file\n";

my $found = 0;
my $entry = '';
my @entries = ();
while (my $line = <F>) {
    if ($line eq "\n") {
        if ($found == 1) {
            push @entries, $entry;
        }
        $entry = '';
        $found = 0;
        next;
    }
    $entry .= $line;
    if ($flag eq '-u') {
        if ($line =~ /^sAMAccountName: $text\n$/si) {
            $found = 1;
        }
    }
    elsif($flag eq '-fn') {
        if ($line =~ /^givenName: $text\n$/si) {
            $found = 1;
        }
    }
    elsif($flag eq '-ln') {
        if ($line =~ /^sn: $text\n$/si) {
            $found = 1;
        }
    }
    else {
        if (  ($line =~ /^cn: $text\n$/si)
           || ($line =~ /^sn: $text\n$/si)
           || ($line =~ /^givenName: $text\n$/si)
           || ($line =~ /^displayName: $text\n$/si)
           || ($line =~ /^sAMAccountName: $text\n$/si)
           ) {
            $found = 1;
        }
    }
}
close F;

if ($found == 1) {
    push @entries, $entry;
}

print join "\n", @entries;
print "\n";
