#!/bin/bash
cat <<'EOF'


# https://medium.com/@enthu.cutlet/how-to-mount-google-drive-on-linux-windows-systems-5ef4bff24288

sudo add-apt-repository ppa:alessandro-strada/ppa
sudo apt update && sudo apt install google-drive-ocamlfuse

google-drive-ocamlfuse

mkdir ~/G
google-drive-ocamlfuse ~/G
fusermount -u ~/G


EOF
