#!/bin/bash
docker rm -f rla
rl -c rla echo
scp ~/b/om/raw/Miniconda3-py313_26.3.2-2-Linux-aarch64.sh rla:.
ssh -t rla 'bash ~/Miniconda3-py313_26.3.2-2-Linux-aarch64.sh -b -c'
ssh -t rla 'curl -fsSL https://antigravity.google/cli/install.sh | bash'
ssh -t rla 'rm ~/Miniconda3-py313_26.3.2-2-Linux-aarch64.sh; mkdir ~/x'
echo 'sh rla -> cd ~/x -> agy'
