#!/bin/bash
cont=CODEX
docker rm -f $cont
rl -c $cont echo
scp ~/b/om/raw/Miniconda3-py313_26.3.2-2-Linux-aarch64.sh $cont:.
ssh -t $cont 'bash ~/Miniconda3-py313_26.3.2-2-Linux-aarch64.sh -b -c'
ssh -t $cont 'rm ~/Miniconda3-py313_26.3.2-2-Linux-aarch64.sh; mkdir ~/x'
ssh -t $cont 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
ssh -t $cont 'nvm install v24.18.0'
ssh -t $cont 'nvm alias default v24.18.0'
ssh -t $cont 'npm i -g @openai/codex'
ssh -t $cont 'sudo dnf install -y bubblewrap'
echo "ssh $cont -> cd ~/x -> codex"
